import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import { Provider } from "jotai";
import HydrateAtoms from "./HydrateAtoms";
import { getModels } from "@/lib/services/models";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const models = await getModels();
    const datasets: Dataset[] = [];

    return (
        <Provider>
            <HydrateAtoms initialModels={models} initialDatasets={datasets}>
                <html lang="en">
                    <body
                        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
                    >
                        <main className="mx-auto w-full lg:max-w-[80%] xl:max-w-[90%] 2xl:max-w-[80%] 3xl:max-w-[1536px] flex flex-col gap-10">
                            <Navbar />
                            {children}
                        </main>
                        <footer className="row-start-3 flex gap-6 flex-wrap items-center justify-center">
                            Small footer to show links for example
                        </footer>
                    </body>
                </html>
            </HydrateAtoms>
        </Provider>
    );
}
